/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.lexer.node;

import org.sablecc.sablecc.syntax3.lexer.analysis.*;

@SuppressWarnings("nls")
public final class ALookahead extends PLookahead
{
    private TLookaheadKeyword _lookaheadKeyword_;
    private TNotKeyword _notKeyword_;
    private PExpression _expression_;

    public ALookahead()
    {
        // Constructor
    }

    public ALookahead(
        @SuppressWarnings("hiding") TLookaheadKeyword _lookaheadKeyword_,
        @SuppressWarnings("hiding") TNotKeyword _notKeyword_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setLookaheadKeyword(_lookaheadKeyword_);

        setNotKeyword(_notKeyword_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new ALookahead(
            cloneNode(this._lookaheadKeyword_),
            cloneNode(this._notKeyword_),
            cloneNode(this._expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALookahead(this);
    }

    public TLookaheadKeyword getLookaheadKeyword()
    {
        return this._lookaheadKeyword_;
    }

    public void setLookaheadKeyword(TLookaheadKeyword node)
    {
        if(this._lookaheadKeyword_ != null)
        {
            this._lookaheadKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lookaheadKeyword_ = node;
    }

    public TNotKeyword getNotKeyword()
    {
        return this._notKeyword_;
    }

    public void setNotKeyword(TNotKeyword node)
    {
        if(this._notKeyword_ != null)
        {
            this._notKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notKeyword_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lookaheadKeyword_)
            + toString(this._notKeyword_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lookaheadKeyword_ == child)
        {
            this._lookaheadKeyword_ = null;
            return;
        }

        if(this._notKeyword_ == child)
        {
            this._notKeyword_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lookaheadKeyword_ == oldChild)
        {
            setLookaheadKeyword((TLookaheadKeyword) newChild);
            return;
        }

        if(this._notKeyword_ == oldChild)
        {
            setNotKeyword((TNotKeyword) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
