/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.lexer.node;

import org.sablecc.sablecc.syntax3.lexer.analysis.*;

@SuppressWarnings("nls")
public final class ARightListReferenceListElement extends PListElement
{
    private PElementReference _elementReference_;
    private TRightKeyword _rightKeyword_;

    public ARightListReferenceListElement()
    {
        // Constructor
    }

    public ARightListReferenceListElement(
        @SuppressWarnings("hiding") PElementReference _elementReference_,
        @SuppressWarnings("hiding") TRightKeyword _rightKeyword_)
    {
        // Constructor
        setElementReference(_elementReference_);

        setRightKeyword(_rightKeyword_);

    }

    @Override
    public Object clone()
    {
        return new ARightListReferenceListElement(
            cloneNode(this._elementReference_),
            cloneNode(this._rightKeyword_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARightListReferenceListElement(this);
    }

    public PElementReference getElementReference()
    {
        return this._elementReference_;
    }

    public void setElementReference(PElementReference node)
    {
        if(this._elementReference_ != null)
        {
            this._elementReference_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elementReference_ = node;
    }

    public TRightKeyword getRightKeyword()
    {
        return this._rightKeyword_;
    }

    public void setRightKeyword(TRightKeyword node)
    {
        if(this._rightKeyword_ != null)
        {
            this._rightKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightKeyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._elementReference_)
            + toString(this._rightKeyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._elementReference_ == child)
        {
            this._elementReference_ = null;
            return;
        }

        if(this._rightKeyword_ == child)
        {
            this._rightKeyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._elementReference_ == oldChild)
        {
            setElementReference((PElementReference) newChild);
            return;
        }

        if(this._rightKeyword_ == oldChild)
        {
            setRightKeyword((TRightKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
