/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.lexer.node;

import java.util.*;
import org.sablecc.sablecc.syntax3.lexer.analysis.*;

@SuppressWarnings("nls")
public final class AUnaryParserPriority extends PParserPriority
{
    private TUnaryKeyword _unaryKeyword_;
    private final LinkedList<TIdentifier> _identifiers_ = new LinkedList<TIdentifier>();

    public AUnaryParserPriority()
    {
        // Constructor
    }

    public AUnaryParserPriority(
        @SuppressWarnings("hiding") TUnaryKeyword _unaryKeyword_,
        @SuppressWarnings("hiding") List<TIdentifier> _identifiers_)
    {
        // Constructor
        setUnaryKeyword(_unaryKeyword_);

        setIdentifiers(_identifiers_);

    }

    @Override
    public Object clone()
    {
        return new AUnaryParserPriority(
            cloneNode(this._unaryKeyword_),
            cloneList(this._identifiers_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnaryParserPriority(this);
    }

    public TUnaryKeyword getUnaryKeyword()
    {
        return this._unaryKeyword_;
    }

    public void setUnaryKeyword(TUnaryKeyword node)
    {
        if(this._unaryKeyword_ != null)
        {
            this._unaryKeyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryKeyword_ = node;
    }

    public LinkedList<TIdentifier> getIdentifiers()
    {
        return this._identifiers_;
    }

    public void setIdentifiers(List<TIdentifier> list)
    {
        this._identifiers_.clear();
        this._identifiers_.addAll(list);
        for(TIdentifier e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unaryKeyword_)
            + toString(this._identifiers_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unaryKeyword_ == child)
        {
            this._unaryKeyword_ = null;
            return;
        }

        if(this._identifiers_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unaryKeyword_ == oldChild)
        {
            setUnaryKeyword((TUnaryKeyword) newChild);
            return;
        }

        for(ListIterator<TIdentifier> i = this._identifiers_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TIdentifier) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
