/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.lexer.node;

public abstract class PAlternativeTransformations extends Node
{
    // Empty body
}
