/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.lexer.node;

import org.sablecc.sablecc.syntax3.lexer.analysis.*;

@SuppressWarnings("nls")
public final class TGrammarKeyword extends Token
{
    public TGrammarKeyword()
    {
        super.setText("Grammar");
    }

    public TGrammarKeyword(int line, int pos)
    {
        super.setText("Grammar");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TGrammarKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGrammarKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TGrammarKeyword text.");
    }
}
