/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.lexer.node;

import org.sablecc.sablecc.syntax3.lexer.analysis.*;

@SuppressWarnings("nls")
public final class TListKeyword extends Token
{
    public TListKeyword()
    {
        super.setText("List");
    }

    public TListKeyword(int line, int pos)
    {
        super.setText("List");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TListKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTListKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TListKeyword text.");
    }
}
