/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.lexer.node;

import org.sablecc.sablecc.syntax3.lexer.analysis.*;

@SuppressWarnings("nls")
public final class TPrecedenceKeyword extends Token
{
    public TPrecedenceKeyword()
    {
        super.setText("Precedence");
    }

    public TPrecedenceKeyword(int line, int pos)
    {
        super.setText("Precedence");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPrecedenceKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrecedenceKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPrecedenceKeyword text.");
    }
}
