/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.lexer.node;

import org.sablecc.sablecc.syntax3.lexer.analysis.*;

@SuppressWarnings("nls")
public final class TRootKeyword extends Token
{
    public TRootKeyword()
    {
        super.setText("Root");
    }

    public TRootKeyword(int line, int pos)
    {
        super.setText("Root");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRootKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRootKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRootKeyword text.");
    }
}
