/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.lexer.node;

import org.sablecc.sablecc.syntax3.lexer.analysis.*;

@SuppressWarnings("nls")
public final class TSelectorKeyword extends Token
{
    public TSelectorKeyword()
    {
        super.setText("Selector");
    }

    public TSelectorKeyword(int line, int pos)
    {
        super.setText("Selector");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSelectorKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSelectorKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSelectorKeyword text.");
    }
}
