/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.lexer.node;

import org.sablecc.sablecc.syntax3.lexer.analysis.*;

@SuppressWarnings("nls")
public final class TUnaryKeyword extends Token
{
    public TUnaryKeyword()
    {
        super.setText("Unary");
    }

    public TUnaryKeyword(int line, int pos)
    {
        super.setText("Unary");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUnaryKeyword(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUnaryKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUnaryKeyword text.");
    }
}
