/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.sablecc.sablecc.syntax3.lexer.lexer;

import java.io.*;
import org.sablecc.sablecc.syntax3.lexer.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private PushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    protected final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") PushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 62:
                        {
                            @SuppressWarnings("hiding") Token token = new62(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 63:
                        {
                            @SuppressWarnings("hiding") Token token = new63(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 64:
                        {
                            @SuppressWarnings("hiding") Token token = new64(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 65:
                        {
                            @SuppressWarnings("hiding") Token token = new65(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 66:
                        {
                            @SuppressWarnings("hiding") Token token = new66(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 67:
                        {
                            @SuppressWarnings("hiding") Token token = new67(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 68:
                        {
                            @SuppressWarnings("hiding") Token token = new68(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 69:
                        {
                            @SuppressWarnings("hiding") Token token = new69(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 70:
                        {
                            @SuppressWarnings("hiding") Token token = new70(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 71:
                        {
                            @SuppressWarnings("hiding") Token token = new71(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 72:
                        {
                            @SuppressWarnings("hiding") Token token = new72(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 73:
                        {
                            @SuppressWarnings("hiding") Token token = new73(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAlternativeKeyword(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAndKeyword(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnyKeyword(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TContextKeyword(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDanglingKeyword(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEmptyKeyword(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEndKeyword(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TExceptKeyword(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGrammarKeyword(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGroupKeyword(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgnoredKeyword(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInvestigatorKeyword(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeftKeyword(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLexerKeyword(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TListKeyword(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLongestKeyword(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLookaheadKeyword(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLookbackKeyword(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNotKeyword(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNewKeyword(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNullKeyword(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParserKeyword(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrecedenceKeyword(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProductionKeyword(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRightKeyword(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRootKeyword(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSelectorKeyword(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSeparatorKeyword(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShortestKeyword(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStartKeyword(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTokenKeyword(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTransformationKeyword(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTreeKeyword(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnaryKeyword(line, pos); }
    Token new34(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }
    Token new35(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAlternativeName(text, line, pos); }
    Token new36(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElementName(text, line, pos); }
    Token new37(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEpsilon(text, line, pos); }
    Token new38(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChar(text, line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDecChar(text, line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new THexChar(text, line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssign(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TArrow(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBar(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaret(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGt(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TQMark(line, pos); }
    Token new56(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStar(line, pos); }
    Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThreeDots(line, pos); }
    Token new59(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTwoDots(line, pos); }
    Token new60(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new61(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLineComment(text, line, pos); }
    Token new62(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLongComment(text, line, pos); }
    Token new63(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCtrlZ(text, line, pos); }
    Token new64(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInvalidKeyword(text, line, pos); }
    Token new65(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInvalidNumber(text, line, pos); }
    Token new66(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInvalidNormalIdentifier(text, line, pos); }
    Token new67(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInvalidRichIdentifier(text, line, pos); }
    Token new68(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInvalidString(text, line, pos); }
    Token new69(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInvalidHexChar(text, line, pos); }
    Token new70(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInvalidDecChar(text, line, pos); }
    Token new71(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInvalidAlternativeName(text, line, pos); }
    Token new72(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInvalidElementName(text, line, pos); }
    Token new73(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInvalidCharacter(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 8, 1}, {9, 13, 2}, {14, 25, 1}, {26, 26, 3}, {27, 31, 1}, {32, 32, 2}, {33, 34, 1}, {35, 35, 4}, {36, 38, 1}, {39, 39, 5}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {46, 46, 12}, {47, 47, 13}, {48, 57, 14}, {58, 58, 15}, {59, 59, 16}, {60, 60, 17}, {61, 61, 18}, {62, 62, 19}, {63, 63, 20}, {64, 64, 1}, {65, 65, 21}, {66, 66, 22}, {67, 67, 23}, {68, 68, 24}, {69, 69, 25}, {70, 70, 22}, {71, 71, 26}, {72, 72, 22}, {73, 73, 27}, {74, 75, 22}, {76, 76, 28}, {77, 77, 22}, {78, 78, 29}, {79, 79, 22}, {80, 80, 30}, {81, 81, 22}, {82, 82, 31}, {83, 83, 32}, {84, 84, 33}, {85, 85, 34}, {86, 90, 22}, {91, 91, 35}, {92, 93, 1}, {94, 94, 36}, {95, 95, 37}, {96, 96, 1}, {97, 122, 38}, {123, 123, 39}, {124, 124, 40}, {125, 65535, 1}, },
            {},
            {{9, 13, 41}, {32, 32, 41}, },
            {},
            {{43, 43, 42}, {45, 45, 42}, {48, 57, 43}, {65, 87, 44}, {88, 88, 45}, {89, 90, 44}, {95, 95, 44}, {97, 119, 44}, {120, 120, 45}, {121, 122, 44}, },
            {{9, 9, 46}, {32, 38, 46}, {39, 39, 47}, {40, 91, 46}, {92, 92, 48}, {93, 126, 46}, },
            {},
            {},
            {},
            {},
            {},
            {{62, 62, 49}, },
            {{46, 46, 50}, },
            {{42, 42, 51}, {47, 47, 52}, },
            {{48, 57, 53}, {65, 90, 54}, {95, 95, 54}, {97, 122, 54}, },
            {},
            {},
            {{48, 57, 55}, {65, 90, 56}, {95, 95, 55}, {97, 122, 56}, },
            {},
            {},
            {},
            {{48, 57, 57}, {65, 90, 57}, {95, 95, 57}, {97, 107, 57}, {108, 108, 58}, {109, 109, 57}, {110, 110, 59}, {111, 122, 57}, },
            {{48, 95, -23}, {97, 122, 57}, },
            {{48, 95, -23}, {97, 110, 57}, {111, 111, 60}, {112, 122, 57}, },
            {{48, 95, -23}, {97, 97, 61}, {98, 122, 57}, },
            {{48, 95, -23}, {97, 108, 57}, {109, 109, 62}, {110, 110, 63}, {111, 119, 57}, {120, 120, 64}, {121, 122, 57}, },
            {{48, 95, -23}, {97, 113, 57}, {114, 114, 65}, {115, 122, 57}, },
            {{48, 95, -23}, {97, 102, 57}, {103, 103, 66}, {104, 109, 57}, {110, 110, 67}, {111, 122, 57}, },
            {{48, 95, -23}, {97, 100, 57}, {101, 101, 68}, {102, 104, 57}, {105, 105, 69}, {106, 110, 57}, {111, 111, 70}, {112, 122, 57}, },
            {{48, 100, -30}, {101, 101, 71}, {102, 110, 57}, {111, 111, 72}, {112, 116, 57}, {117, 117, 73}, {118, 122, 57}, },
            {{48, 95, -23}, {97, 97, 74}, {98, 113, 57}, {114, 114, 75}, {115, 122, 57}, },
            {{48, 95, -23}, {97, 104, 57}, {105, 105, 76}, {106, 110, 57}, {111, 111, 77}, {112, 122, 57}, },
            {{48, 100, -30}, {101, 101, 78}, {102, 103, 57}, {104, 104, 79}, {105, 115, 57}, {116, 116, 80}, {117, 122, 57}, },
            {{48, 110, -25}, {111, 111, 81}, {112, 113, 57}, {114, 114, 82}, {115, 122, 57}, },
            {{48, 95, -23}, {97, 109, 57}, {110, 110, 83}, {111, 122, 57}, },
            {{48, 57, 84}, {60, 60, 85}, {65, 90, 84}, {95, 95, 84}, {97, 122, 86}, },
            {},
            {{48, 57, 87}, {65, 90, 87}, {95, 95, 87}, {97, 122, 87}, },
            {{48, 57, 88}, {65, 90, 87}, {95, 95, 89}, {97, 122, 90}, },
            {{48, 57, 91}, {60, 60, 92}, {65, 90, 91}, {95, 95, 91}, {97, 122, 93}, },
            {},
            {{9, 32, -4}, },
            {{48, 57, 43}, {65, 90, 44}, {95, 95, 44}, {97, 122, 44}, },
            {{48, 122, -44}, },
            {{48, 57, 44}, {65, 122, -44}, },
            {{43, 43, 94}, {45, 45, 94}, {48, 57, 95}, {65, 70, 95}, {71, 90, 96}, {95, 95, 96}, {97, 102, 95}, {103, 122, 96}, },
            {{9, 9, 97}, {32, 38, 97}, {39, 39, 98}, {40, 91, 97}, {92, 92, 99}, {93, 126, 97}, },
            {},
            {{39, 39, 100}, {92, 92, 100}, },
            {},
            {{46, 46, 101}, },
            {{9, 13, 102}, {32, 41, 102}, {42, 42, 103}, {43, 126, 102}, },
            {{9, 9, 104}, {10, 12, 105}, {13, 13, 106}, {32, 126, 104}, },
            {{48, 122, -16}, },
            {{48, 57, 54}, {65, 122, -16}, },
            {{48, 57, 55}, {65, 90, 55}, {95, 95, 55}, {97, 122, 55}, },
            {{48, 57, 107}, {62, 62, 108}, {65, 90, 107}, {95, 95, 55}, {97, 122, 107}, },
            {{48, 122, -24}, },
            {{48, 95, -23}, {97, 115, 57}, {116, 116, 109}, {117, 122, 57}, },
            {{48, 95, -23}, {97, 99, 57}, {100, 100, 110}, {101, 120, 57}, {121, 121, 111}, {122, 122, 57}, },
            {{48, 109, -36}, {110, 110, 112}, {111, 122, 57}, },
            {{48, 109, -36}, {110, 110, 113}, {111, 122, 57}, },
            {{48, 95, -23}, {97, 111, 57}, {112, 112, 114}, {113, 122, 57}, },
            {{48, 99, -61}, {100, 100, 115}, {101, 122, 57}, },
            {{48, 95, -23}, {97, 98, 57}, {99, 99, 116}, {100, 122, 57}, },
            {{48, 95, -23}, {97, 97, 117}, {98, 110, 57}, {111, 111, 118}, {112, 122, 57}, },
            {{48, 109, -36}, {110, 110, 119}, {111, 122, 57}, },
            {{48, 95, -23}, {97, 117, 57}, {118, 118, 120}, {119, 122, 57}, },
            {{48, 95, -23}, {97, 101, 57}, {102, 102, 121}, {103, 119, 57}, {120, 120, 122}, {121, 122, 57}, },
            {{48, 95, -23}, {97, 114, 57}, {115, 115, 123}, {116, 122, 57}, },
            {{48, 109, -36}, {110, 110, 124}, {111, 111, 125}, {112, 122, 57}, },
            {{48, 95, -23}, {97, 118, 57}, {119, 119, 126}, {120, 122, 57}, },
            {{48, 115, -60}, {116, 116, 127}, {117, 122, 57}, },
            {{48, 107, -23}, {108, 108, 128}, {109, 122, 57}, },
            {{48, 113, -28}, {114, 114, 129}, {115, 122, 57}, },
            {{48, 100, -30}, {101, 101, 130}, {102, 110, 57}, {111, 111, 131}, {112, 122, 57}, },
            {{48, 102, -29}, {103, 103, 132}, {104, 122, 57}, },
            {{48, 110, -25}, {111, 111, 133}, {112, 122, 57}, },
            {{48, 107, -23}, {108, 108, 134}, {109, 111, 57}, {112, 112, 135}, {113, 122, 57}, },
            {{48, 110, -25}, {111, 111, 136}, {112, 122, 57}, },
            {{48, 95, -23}, {97, 97, 137}, {98, 122, 57}, },
            {{48, 95, -23}, {97, 106, 57}, {107, 107, 138}, {108, 122, 57}, },
            {{48, 95, -23}, {97, 97, 139}, {98, 100, 57}, {101, 101, 140}, {102, 122, 57}, },
            {{48, 95, -23}, {97, 97, 141}, {98, 122, 57}, },
            {{48, 57, 84}, {65, 95, -37}, {97, 122, 84}, },
            {{48, 57, 84}, {65, 90, 142}, {95, 95, 84}, {97, 122, 142}, },
            {{48, 57, 143}, {58, 58, 144}, {65, 90, 84}, {95, 95, 145}, {97, 122, 146}, },
            {{48, 122, -39}, },
            {{48, 122, -40}, },
            {{48, 95, -39}, {97, 122, 147}, },
            {{48, 122, -40}, },
            {{48, 57, 91}, {65, 95, -41}, {97, 122, 91}, },
            {{48, 57, 91}, {65, 90, 148}, {95, 95, 91}, {97, 122, 148}, },
            {{48, 57, 149}, {58, 58, 150}, {65, 90, 91}, {95, 95, 151}, {97, 122, 152}, },
            {{48, 57, 153}, {65, 70, 153}, {71, 90, 154}, {95, 95, 154}, {97, 102, 153}, {103, 122, 154}, },
            {{48, 122, -47}, },
            {{48, 57, 96}, {65, 90, 96}, {95, 95, 96}, {97, 122, 96}, },
            {{9, 38, -48}, {39, 39, 155}, {40, 126, -48}, },
            {},
            {{39, 39, 156}, {92, 92, 156}, },
            {{9, 126, -48}, },
            {},
            {{9, 126, -53}, },
            {{9, 13, 157}, {32, 41, 157}, {42, 42, 103}, {43, 46, 157}, {47, 47, 158}, {48, 126, 157}, },
            {{9, 126, -54}, },
            {},
            {{10, 10, 159}, },
            {{48, 122, -58}, },
            {},
            {{48, 100, -30}, {101, 101, 160}, {102, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 115, -60}, {116, 116, 161}, {117, 122, 57}, },
            {{48, 102, -29}, {103, 103, 162}, {104, 122, 57}, },
            {{48, 115, -60}, {116, 116, 163}, {117, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 100, -30}, {101, 101, 164}, {102, 122, 57}, },
            {{48, 108, -27}, {109, 109, 165}, {110, 122, 57}, },
            {{48, 95, -23}, {97, 116, 57}, {117, 117, 166}, {118, 122, 57}, },
            {{48, 110, -25}, {111, 111, 167}, {112, 122, 57}, },
            {{48, 100, -30}, {101, 101, 168}, {102, 122, 57}, },
            {{48, 115, -60}, {116, 116, 169}, {117, 122, 57}, },
            {{48, 100, -30}, {101, 101, 170}, {102, 122, 57}, },
            {{48, 115, -60}, {116, 116, 171}, {117, 122, 57}, },
            {{48, 102, -29}, {103, 103, 172}, {104, 122, 57}, },
            {{48, 106, -83}, {107, 107, 173}, {108, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 107, -23}, {108, 108, 174}, {109, 122, 57}, },
            {{48, 114, -71}, {115, 115, 175}, {116, 122, 57}, },
            {{48, 98, -66}, {99, 99, 176}, {100, 122, 57}, },
            {{48, 99, -61}, {100, 100, 177}, {101, 122, 57}, },
            {{48, 95, -23}, {97, 103, 57}, {104, 104, 178}, {105, 122, 57}, },
            {{48, 115, -60}, {116, 116, 179}, {117, 122, 57}, },
            {{48, 100, -30}, {101, 101, 180}, {102, 122, 57}, },
            {{48, 95, -23}, {97, 97, 181}, {98, 122, 57}, },
            {{48, 113, -28}, {114, 114, 182}, {115, 122, 57}, },
            {{48, 113, -28}, {114, 114, 183}, {115, 122, 57}, },
            {{48, 100, -30}, {101, 101, 184}, {102, 122, 57}, },
            {{48, 109, -36}, {110, 110, 185}, {111, 122, 57}, },
            {{48, 100, -30}, {101, 101, 186}, {102, 122, 57}, },
            {{48, 113, -28}, {114, 114, 187}, {115, 122, 57}, },
            {{48, 57, 188}, {62, 62, 189}, {65, 90, 188}, {95, 95, 84}, {97, 122, 188}, },
            {{48, 122, -88}, },
            {{93, 93, 190}, },
            {{48, 95, -86}, {97, 122, 191}, },
            {{48, 122, -88}, },
            {{48, 57, 192}, {65, 95, -40}, {97, 122, 193}, },
            {{48, 57, 194}, {62, 62, 195}, {65, 90, 194}, {95, 95, 91}, {97, 122, 194}, },
            {{48, 122, -95}, },
            {{125, 125, 196}, },
            {{48, 95, -93}, {97, 122, 197}, },
            {{48, 122, -95}, },
            {{48, 122, -96}, },
            {{48, 57, 154}, {65, 90, 154}, {95, 95, 154}, {97, 122, 154}, },
            {},
            {{9, 126, -99}, },
            {{9, 13, 198}, {32, 41, 198}, {42, 42, 103}, {43, 126, 198}, },
            {},
            {},
            {{48, 113, -28}, {114, 114, 199}, {115, 122, 57}, },
            {{48, 100, -30}, {101, 101, 200}, {102, 122, 57}, },
            {{48, 107, -23}, {108, 108, 201}, {109, 122, 57}, },
            {{48, 95, -23}, {97, 120, 57}, {121, 121, 202}, {122, 122, 57}, },
            {{48, 111, -64}, {112, 112, 203}, {113, 122, 57}, },
            {{48, 108, -27}, {109, 109, 204}, {110, 122, 57}, },
            {{48, 111, -64}, {112, 112, 205}, {113, 122, 57}, },
            {{48, 113, -28}, {114, 114, 206}, {115, 122, 57}, },
            {{48, 114, -71}, {115, 115, 207}, {116, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 113, -28}, {114, 114, 208}, {115, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 100, -30}, {101, 101, 209}, {102, 122, 57}, },
            {{48, 95, -23}, {97, 97, 210}, {98, 98, 211}, {99, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 100, -30}, {101, 101, 212}, {102, 122, 57}, },
            {{48, 100, -30}, {101, 101, 213}, {102, 122, 57}, },
            {{48, 116, -120}, {117, 117, 214}, {118, 122, 57}, },
            {{48, 115, -60}, {116, 116, 215}, {117, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 98, -66}, {99, 99, 216}, {100, 122, 57}, },
            {{48, 113, -28}, {114, 114, 217}, {115, 122, 57}, },
            {{48, 115, -60}, {116, 116, 218}, {117, 122, 57}, },
            {{48, 115, -60}, {116, 116, 219}, {117, 122, 57}, },
            {{48, 109, -36}, {110, 110, 220}, {111, 122, 57}, },
            {{48, 114, -71}, {115, 115, 221}, {116, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 120, -165}, {121, 121, 222}, {122, 122, 57}, },
            {{48, 122, -144}, },
            {{58, 58, 144}, },
            {},
            {{48, 57, 223}, {58, 95, -88}, {97, 122, 224}, },
            {{48, 122, -149}, },
            {{48, 122, -149}, },
            {{48, 122, -150}, },
            {{58, 58, 150}, },
            {},
            {{48, 57, 225}, {58, 95, -95}, {97, 122, 226}, },
            {{9, 126, -159}, },
            {{48, 109, -36}, {110, 110, 227}, {111, 122, 57}, },
            {{48, 95, -23}, {97, 119, 57}, {120, 120, 228}, {121, 122, 57}, },
            {{48, 104, -33}, {105, 105, 229}, {106, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 115, -60}, {116, 116, 230}, {117, 122, 57}, },
            {{48, 95, -23}, {97, 97, 231}, {98, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 100, -30}, {101, 101, 232}, {102, 122, 57}, },
            {{48, 115, -60}, {116, 116, 233}, {117, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 114, -71}, {115, 115, 234}, {116, 122, 57}, },
            {{48, 103, -134}, {104, 104, 235}, {105, 122, 57}, },
            {{48, 95, -23}, {97, 97, 236}, {98, 122, 57}, },
            {{48, 113, -28}, {114, 114, 237}, {115, 122, 57}, },
            {{48, 99, -61}, {100, 100, 238}, {101, 122, 57}, },
            {{48, 98, -66}, {99, 99, 239}, {100, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 115, -60}, {116, 116, 240}, {117, 122, 57}, },
            {{48, 95, -23}, {97, 97, 241}, {98, 122, 57}, },
            {{48, 100, -30}, {101, 101, 242}, {102, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 101, -70}, {102, 102, 243}, {103, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 122, -193}, },
            {{48, 122, -193}, },
            {{48, 122, -199}, },
            {{48, 122, -199}, },
            {{48, 95, -23}, {97, 97, 244}, {98, 122, 57}, },
            {{48, 115, -60}, {116, 116, 245}, {117, 122, 57}, },
            {{48, 109, -36}, {110, 110, 246}, {111, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 113, -28}, {114, 114, 247}, {115, 122, 57}, },
            {{48, 99, -61}, {100, 100, 248}, {101, 122, 57}, },
            {{48, 104, -33}, {105, 105, 249}, {106, 122, 57}, },
            {{48, 115, -60}, {116, 116, 250}, {117, 122, 57}, },
            {{48, 100, -30}, {101, 101, 251}, {102, 122, 57}, },
            {{48, 98, -66}, {99, 99, 252}, {100, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 100, -30}, {101, 101, 253}, {102, 122, 57}, },
            {{48, 115, -60}, {116, 116, 254}, {117, 122, 57}, },
            {{48, 110, -25}, {111, 111, 255}, {112, 122, 57}, },
            {{48, 115, -60}, {116, 116, 256}, {117, 122, 57}, },
            {{48, 114, -71}, {115, 115, 257}, {116, 122, 57}, },
            {{48, 110, -25}, {111, 111, 258}, {112, 122, 57}, },
            {{48, 115, -60}, {116, 116, 259}, {117, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 102, -29}, {103, 103, 260}, {104, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 102, -29}, {103, 103, 261}, {104, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 95, -23}, {97, 97, 262}, {98, 122, 57}, },
            {{48, 106, -83}, {107, 107, 263}, {108, 122, 57}, },
            {{48, 109, -36}, {110, 110, 264}, {111, 122, 57}, },
            {{48, 104, -33}, {105, 105, 265}, {106, 122, 57}, },
            {{48, 113, -28}, {114, 114, 266}, {115, 122, 57}, },
            {{48, 110, -25}, {111, 111, 267}, {112, 122, 57}, },
            {{48, 115, -60}, {116, 116, 268}, {117, 122, 57}, },
            {{48, 113, -28}, {114, 114, 269}, {115, 122, 57}, },
            {{48, 104, -33}, {105, 105, 270}, {106, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 95, -23}, {97, 97, 271}, {98, 122, 57}, },
            {{48, 99, -61}, {100, 100, 272}, {101, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 98, -66}, {99, 99, 273}, {100, 122, 57}, },
            {{48, 110, -25}, {111, 111, 274}, {112, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 113, -28}, {114, 114, 275}, {115, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 108, -27}, {109, 109, 276}, {110, 122, 57}, },
            {{48, 117, -69}, {118, 118, 277}, {119, 122, 57}, },
            {{48, 115, -60}, {116, 116, 278}, {117, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 100, -30}, {101, 101, 279}, {102, 122, 57}, },
            {{48, 109, -36}, {110, 110, 280}, {111, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 95, -23}, {97, 97, 281}, {98, 122, 57}, },
            {{48, 100, -30}, {101, 101, 282}, {102, 122, 57}, },
            {{48, 110, -25}, {111, 111, 283}, {112, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 115, -60}, {116, 116, 284}, {117, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 113, -28}, {114, 114, 285}, {115, 122, 57}, },
            {{48, 104, -33}, {105, 105, 286}, {106, 122, 57}, },
            {{48, 122, -24}, },
            {{48, 110, -25}, {111, 111, 287}, {112, 122, 57}, },
            {{48, 109, -36}, {110, 110, 288}, {111, 122, 57}, },
            {{48, 122, -24}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 73, 60, 63, 70, 68, 43, 44, 57, 54, 50, 53, 51, 73, 40, 49, 56, 67, 45, 52, 55, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 72, 48, 66, 34, 71, 47, 60, 70, 41, 70, 69, 68, 37, -1, 46, 59, -1, 61, 40, 65, 67, 67, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 72, 72, 72, 66, 34, 66, 34, 71, 71, 71, 69, 42, 69, 68, 38, -1, 68, 58, -1, -1, 61, 61, 61, 67, 34, 64, 1, 2, 64, 64, 64, 6, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 19, 18, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 72, 72, -1, 72, 72, 34, 71, 71, -1, 71, 71, 42, 69, 39, 68, -1, 62, 61, 64, 64, 64, 64, 64, 64, 64, 64, 64, 12, 64, 14, 64, 64, 20, 64, 64, 64, 64, 25, 64, 64, 64, 64, 64, 64, 32, 64, 72, -1, 36, 72, 34, 34, 71, -1, 35, 71, -1, 64, 64, 64, 5, 64, 64, 9, 64, 64, 13, 64, 64, 64, 64, 64, 64, 24, 64, 64, 64, 29, 30, 64, 33, 72, 72, 71, 71, 64, 64, 64, 7, 64, 64, 64, 64, 64, 64, 21, 64, 64, 64, 64, 64, 64, 64, 3, 64, 8, 10, 64, 15, 64, 64, 64, 64, 64, 64, 64, 64, 64, 4, 64, 64, 17, 64, 64, 26, 64, 28, 64, 64, 64, 16, 64, 64, 27, 64, 64, 64, 22, 23, 64, 0, 64, 64, 11, 64, 64, 31, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
